"""
Run the FEniCS 2D-solid (VABS-equivalent) cross-sectional analysis on a single
2D-solid YAML and print the Timoshenko 6x6 stiffness matrix.

This is the self-contained driver behind the MSG thin-walled benchmark's solid
reference.  It mirrors ``examples/1_get_beam_props_from_solid_cross_section.py``
but takes the mesh path on the command line so any of the cases in ``meshes/``
(generated by ``generate_solid_meshes.py``) can be run on their own.

Usage (inside the FEniCSx/opensg env):
    python run_solid_timo_from_yaml.py meshes/stripthick_iso_h0.5_W1.0.yaml
    python run_solid_timo_from_yaml.py meshes/tube_iso_hR0.06.yaml

The 6x6 is ordered [ext, shear2, shear3, twist, bend2, bend3], i.e. the diagonal
is [EA, GA2, GA3, GJ, EI2, EI3].
"""
import os
import sys
import time
import numpy as np

from opensg.mesh.segment import SolidBounMesh
from opensg.core.solid import compute_timo_boun
import opensg.utils.solid as utils

DIAG = ["C11 (EA)", "C22 (GA2)", "C33 (GA3)", "C44 (GJ)", "C55 (EI2)", "C66 (EI3)"]


def main(mesh_yaml):
    tic = time.time()
    segment_mesh = SolidBounMesh(mesh_yaml)
    material_parameters, density = segment_mesh.material_database
    meshdata = segment_mesh.meshdata

    C6 = np.asarray(compute_timo_boun(material_parameters, meshdata)[0])
    mass = utils.get_mass_solid(meshdata, density)

    np.set_printoptions(precision=4, suppress=False, linewidth=160)
    print(f"\nMesh        : {os.path.basename(mesh_yaml)}")
    print(f"Boundary origin: {meshdata['origin']}")
    print("\nTimoshenko 6x6 [ext, shear2, shear3, twist, bend2, bend3]:")
    print(C6)
    print("\nDiagonal (engineering):")
    for lbl, v in zip(DIAG, np.diag(C6)):
        print(f"  {lbl:11s} = {v: .6e}")
    print("\n2D mass matrix:")
    print(np.asarray(mass))
    print(f"\nTime: {time.time() - tic:.1f} s")
    return C6


if __name__ == "__main__":
    yaml_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "meshes", "stripthick_iso_h0.5_W1.0.yaml")
    main(yaml_path)
